
[package]
authors = ["phiresky <phireskyde+git@gmail.com>"]
description = "rga: ripgrep, but also search in PDFs, E-Books, Office documents, zip, tar.gz, etc."
edition = "2021"
exclude = [
  "exampledir/*",
]
homepage = "https://github.com/phiresky/ripgrep-all"
license = "AGPL-3.0-or-later"
name = "ripgrep_all"
readme = "README.md"
repository = "https://github.com/phiresky/ripgrep-all"
version = "1.0.0-alpha.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = {version = "1.0.32", features = ["backtrace"]}
async-compression = {version = "0.3.15", features = ["all", "all-algorithms", "tokio"]}
async-stream = "0.3.3"
async-trait = "0.1.64"
async_zip = {version = "0.0.12", features = ["full"]}
bincode = "1.3.1"
bytes = "1.2.1"
clap = {version = "4.0.18", features = ["wrap_help"]}
crossbeam = "0.8.1"
crossbeam-channel = "0.5.1"
derive_more = "0.99.9"
directories-next = "2.0.0"
dyn-clonable = "0.9.0"
dyn-clone = "1.0.2"
encoding_rs = "0.8.24"
encoding_rs_io = "0.1.7"
env_logger = "0.10.0"
glob = "0.3.0"
json_comments = "0.2.1"
lazy_static = "1.4.0"
log = "0.4.11"
memchr = "2.3.3"
paste = "1.0.0"
path-clean = "0.1.0"
pretty-bytes = "0.2.2"
regex = "1.3.9"
rkv = "0.17" # 0.18 removes lmdb backend
rusqlite = {version = "0.28.0", features = ["vtab", "bundled"]}
schemars = {version = "0.8.0-alpha-4", features = ["preserve_order"]}
serde = {version = "1.0.115", features = ["derive"]}
serde_json = "1.0.57"
size_format = "1.0.2"
structopt = "0.3.17"
tempfile = "3.1.0"
tokio = {version = "1.21.2", features = ["full"]}
tokio-stream = {version = "0.1.11", features = ["io-util", "tokio-util"]}
tokio-tar = { git = "https://github.com/vorot93/tokio-tar", version = "0.3.0" }
tokio-util = {version = "0.7.4", features = ["io", "full"]}
tree_magic = {package = "tree_magic_mini", version = "3.0.0"}

[dev-dependencies]
async-recursion = "1.0.0"
ctor = "0.1.20"
pretty_assertions = "1.3.0"
tokio-test = "0.4.2"
